#!/usr/bin/env python3
"""KUMA T-Deck background generator (image-based).

Bakes Jax's background art (designs/backgrounds/*.png, native 1448x1086 = 4:3)
down to the T-Deck's 320x240 and emits an embeddable C header
(src/kuma_bg_data.h, drawn via drawPng), plus preview PNGs in assets/.

Mapping (source -> C symbol):
    backg1     -> KUMA_BG_DASH1    selectable home background #1 (default)
    backg2     -> KUMA_BG_DASH2    selectable home background #2
    backgterm  -> KUMA_BG_TERM     terminal background (replaces it entirely)
    battle1    -> KUMA_BG_BATTLE1  battle scene A (alternates per encounter)
    battle2    -> KUMA_BG_BATTLE2  battle scene B
    evochamber -> KUMA_BG_EVO      evolution-chamber backdrop

The two easter-egg backgrounds (backgFLAG / backgFLAG1) are intentionally NOT
baked here - they're delivered through the unlock flow (see docs/easter-eggs).

Run:  python assets/gen_bg.py
"""
import io
import os

from PIL import Image

W, H = 320, 240
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "src"))
ART = os.path.normpath(os.path.join(HERE, "..", "..", "..", "designs", "backgrounds"))

# (source stem, C symbol, preview filename)
ASSETS = [
    ("backg1",     "KUMA_BG_DASH1",   "bg_dashboard1.png"),
    ("backg2",     "KUMA_BG_DASH2",   "bg_dashboard2.png"),
    ("backgterm",  "KUMA_BG_TERM",    "bg_terminal.png"),
    ("battle1",    "KUMA_BG_BATTLE1", "bg_battle1.png"),
    ("battle2",    "KUMA_BG_BATTLE2", "bg_battle2.png"),
    ("evochamber", "KUMA_BG_EVO",     "bg_evo.png"),
    # Creator-unit showcase background (creator_mode). Also the README hero bg.
    ("backgFLAG",  "KUMA_BG_FLAG",    "bg_flag.png"),
    # Kuroshuna armed-mode home background (dark shrine / red evil-twin).
    ("kuroshuna",  "KUMA_BG_KURO",    "bg_kuroshuna.png"),
]


def fit(stem):
    """Load a source 4:3 image and resize to exactly 320x240 (LANCZOS)."""
    im = Image.open(os.path.join(ART, stem + ".png")).convert("RGB")
    # sources are 4:3; if a future one isn't, cover-crop to 320x240 first
    if abs(im.width / im.height - W / H) > 0.01:
        scale = max(W / im.width, H / im.height)
        nw, nh = round(im.width * scale), round(im.height * scale)
        im = im.resize((nw, nh), Image.LANCZOS).crop(
            ((nw - W) // 2, (nh - H) // 2, (nw - W) // 2 + W, (nh - H) // 2 + H))
        return im
    return im.resize((W, H), Image.LANCZOS)


def png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def emit_header(variants):
    lines = [
        "// KUMA Guard T-Deck - backgrounds (generated by assets/gen_bg.py from",
        "// designs/backgrounds/*.png; do not edit by hand). 320x240 RGB PNGs, drawPng.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "static const uint16_t KUMA_BG_W = 320, KUMA_BG_H = 240;",
        "",
    ]
    for name, data in variants:
        body = ",".join(str(b) for b in data)
        lines.append(f"static const uint8_t {name}[] = {{{body}}};")
        lines.append(f"static const size_t {name}_LEN = sizeof {name};")
        lines.append("")
    out = os.path.join(SRC, "kuma_bg_data.h")
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))
    return out


def main():
    variants = []
    for stem, sym, preview in ASSETS:
        img = fit(stem)
        img.save(os.path.join(HERE, preview))
        data = png_bytes(img)
        variants.append((sym, data))
    hdr = emit_header(variants)
    total = sum(len(d) for _, d in variants)
    print(f"wrote {hdr}")
    for sym, d in variants:
        print(f"  {sym}: {len(d)} bytes ({len(d)/1024:.1f} KB)")
    print(f"  total embedded: {total} bytes ({total/1024:.1f} KB)")


if __name__ == "__main__":
    main()
