#!/usr/bin/env python3
"""KUMA evolution sprite-pack generator.

Bakes the 5 evolved KUMA forms (designs/sprites/evo1..evo5) into an embeddable C
header (src/evo_sprites_data.h) so the T-Deck can show the right form for the
active sprite_set reported by /api/status. Each pack contains the same 7 frames
the base BEAR_SPRITES pack uses, in the SAME order (so bearSpriteIndex /
modeSpriteIndex map 1:1 across packs):

    0 hibernating  1 foraging  2 sentinel  3 honey  4 apex  5 alert  6 investigating

The evo art is already pre-cut with transparency, so we only trim + normalize to
128px tall (matching the base pack). Reuses the BearSprite struct from
bear_sprites_data.h, so include this header AFTER it.

Run:  python assets/gen_evo.py
"""
import io
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "src"))
ART = os.path.normpath(os.path.join(HERE, "..", "..", "..", "designs", "sprites"))

PACKS = ["evo1", "evo2", "evo3", "evo4", "evo5"]
# 7 frames in bearSpriteIndex order
FRAMES = ["01_hibernating", "02_foraging", "03_sentinel", "04_honey",
          "05_apex", "06_alert", "07_investigating"]
TARGET_H = 128


def fit(path):
    im = Image.open(path).convert("RGBA")
    bbox = im.getbbox()              # trim transparent margins
    if bbox:
        im = im.crop(bbox)
    w, h = im.size
    return im.resize((max(1, round(w * TARGET_H / h)), TARGET_H), Image.LANCZOS)


def png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def main():
    lines = [
        "// KUMA Guard T-Deck - evolution sprite packs evo1..evo5 (generated by",
        "// assets/gen_evo.py from designs/sprites/evoN/*.png; do not hand-edit).",
        "// 128px-tall RGBA PNGs, drawn via drawPng. Reuses the BearSprite struct",
        "// from bear_sprites_data.h, so include this AFTER it.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    total = 0
    arrays = []
    for pi, pack in enumerate(PACKS, 1):
        syms = []
        for fi, frame in enumerate(FRAMES, 1):
            img = fit(os.path.join(ART, pack, frame + ".png"))
            data = png_bytes(img)
            total += len(data)
            sym = f"EVO{pi}_{fi:02d}"
            syms.append((sym, img.size))
            body = ",".join(str(b) for b in data)
            lines.append(f"static const uint8_t {sym}[] = {{{body}}};")
        lines.append("")
        arr = ",\n".join(
            f"  {{{s}, sizeof {s}, {wh[0]}, {wh[1]}}}" for s, wh in syms)
        arrays.append(
            f"static const BearSprite EVO{pi}_SPRITES[7] = {{\n{arr}\n}};")
    lines.extend(arrays)
    lines.append("")
    # Pack selector: sprite_set string -> the matching 7-sprite pack, or nullptr
    # (caller falls back to BEAR_SPRITES for "states"/unknown).
    lines.append("static inline const BearSprite* evoPackFor(const char* set) {")
    for pi, pack in enumerate(PACKS, 1):
        lines.append(f'  if (!strcmp(set, "{pack}")) return EVO{pi}_SPRITES;')
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")

    out = os.path.join(SRC, "evo_sprites_data.h")
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}")
    print(f"  5 packs x 7 frames = 35 sprites, {total} bytes ({total/1024:.1f} KB)")


if __name__ == "__main__":
    main()
