#!/usr/bin/env python3
"""KUMA -> KUROSHUNA (Dark Shuna apex) sprite + wordmark generator.

Bakes the single apex_hackback hi-res render into KUROSHUNA_APEX (192px tall,
matching the Shuna per-sprite draw scale) and a クロシュナ wordmark KUROSHUNA_LOGO.
Reuses the gen_shuna white-bg pipeline (flood-fill + pocket removal + defringe).

Run:  python assets/gen_kuroshuna.py
"""
import io
import os

from PIL import Image, ImageDraw, ImageFont

import gen_shuna as S  # reuse flood_key / remove_white_pockets / defringe / POCKET_MIN

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "src"))
ART = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "designs", "sprites", "kuroshuna"))
HIRES = os.path.join(ART, "hires", "apex_hackback.png")
TARGET_H = 192


def process():
    im = Image.open(HIRES).convert("RGBA")
    im = S.defringe(S.remove_white_pockets(S.flood_key(im), min_size=S.POCKET_MIN))
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)
    w, h = im.size
    return im.resize((max(1, round(w * TARGET_H / h)), TARGET_H), Image.LANCZOS)


def render_logo():
    """クロシュナ wordmark, off-white to match KUMA_LOGO; 24px tall."""
    col = (235, 243, 237, 255)
    font = ImageFont.truetype("C:/Windows/Fonts/msgothic.ttc", 30)
    tmp = Image.new("RGBA", (200, 48), (0, 0, 0, 0))
    ImageDraw.Draw(tmp).text((2, 2), "クロシュナ", font=font, fill=col)
    bb = tmp.getbbox()
    im = tmp.crop(bb)
    return im.resize((round(im.width * 24 / im.height), 24), Image.LANCZOS)


def png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def main():
    sp = process()
    sp.save(os.path.join(ART, "apex_hackback.png"))
    logo = render_logo()
    spd, ld = png_bytes(sp), png_bytes(logo)
    lines = [
        "// KUMA Guard T-Deck - KUROSHUNA (Dark Shuna apex) sprite + クロシュナ",
        "// wordmark (generated by assets/gen_kuroshuna.py; do not hand-edit).",
        "// Include AFTER bear_sprites_data.h (reuses BearSprite).",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"static const uint8_t KUROSHUNA_APEX_DATA[] = {{{','.join(str(b) for b in spd)}}};",
        f"static const BearSprite KUROSHUNA_APEX = {{KUROSHUNA_APEX_DATA, "
        f"sizeof KUROSHUNA_APEX_DATA, {sp.size[0]}, {sp.size[1]}}};",
        "",
        f"static const uint8_t KUROSHUNA_LOGO[] = {{{','.join(str(b) for b in ld)}}};",
        f"static const uint16_t KUROSHUNA_LOGO_W = {logo.size[0]}, "
        f"KUROSHUNA_LOGO_H = {logo.size[1]};",
        "",
    ]
    out = os.path.join(SRC, "kuroshuna_sprites_data.h")
    with open(out, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: sprite {sp.size}, logo {logo.size}, "
          f"{(len(spd)+len(ld))/1024:.1f} KB")


if __name__ == "__main__":
    main()
