#!/usr/bin/env python3
"""KUMA offline-animation sprite generator.

Slices the 6-frame "KUMA // OFFLINE" walk/search animation (idle -> check
signal -> no link -> retry -> frustrated -> back to idle) out of Jax's source
sheet, keys out the flat teal background to transparency, trims, normalizes each
frame to 128px tall (matching the base bear sprites), and emits both the per
frame PNGs (designs/sprites/offline/) and an embeddable C header
(src/offline_sprites_data.h, drawn via drawPng like BEAR_SPRITES).

The frames play on the T-Deck home screen when the backend is unreachable, in
place of the old algorithmic grey bear head.

Run:  python assets/gen_offline.py
"""
import io
import math
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", ".."))     # repo root
SRC_SHEET = os.path.join(ROOT, "designs", "sprites", "offline", "_source.png")
OUTDIR = os.path.join(ROOT, "designs", "sprites", "offline")
HDR = os.path.normpath(os.path.join(HERE, "..", "src", "offline_sprites_data.h"))

BG = (2, 108, 123)        # flat teal sheet background
# Kuma's own lightest blue measures ~49 from BG, so the key radius MUST stay
# below that or it eats holes in his body. 40 removes the bg + keeps the bear
# (a faint teal halo on anti-aliased edges is acceptable; holes are not).
KEY_DIST = 40             # color-key radius around BG -> transparent
# ROI spans the full bear incl. the wifi/"!" icon (top ~604) down to the feet
# (~920); the per-frame label text sits at y~988 and is excluded.
ROI_Y0, ROI_Y1 = 652, 924
X_INSET = 12              # skip the per-cell border lines without clipping arms
FRAMES = 6
TARGET_H = 128


def key_bg(cell):
    px = cell.load()
    w, h = cell.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if math.sqrt((r - BG[0]) ** 2 + (g - BG[1]) ** 2 + (b - BG[2]) ** 2) < KEY_DIST:
                px[x, y] = (r, g, b, 0)
    return cell


def extract():
    im = Image.open(SRC_SHEET).convert("RGBA")
    W, _ = im.size
    cellw = W / FRAMES
    frames = []
    for i in range(FRAMES):
        x0 = int(i * cellw) + X_INSET
        x1 = int((i + 1) * cellw) - X_INSET
        cell = key_bg(im.crop((x0, ROI_Y0, x1, ROI_Y1)))
        bbox = cell.getbbox()
        if bbox:
            cell = cell.crop(bbox)
        w, h = cell.size
        cell = cell.resize((max(1, round(w * TARGET_H / h)), TARGET_H), Image.LANCZOS)
        frames.append(cell)
    return frames


def png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def emit_header(frames):
    lines = [
        "// KUMA Guard T-Deck - offline 'searching for signal' animation",
        "// (generated by assets/gen_offline.py from designs/sprites/offline/_source.png;",
        "// do not hand-edit). 128px-tall RGBA PNGs, drawn via drawPng. Reuses the",
        "// BearSprite struct from bear_sprites_data.h, so include this AFTER it.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    for i, f in enumerate(frames, 1):
        data = png_bytes(f)
        body = ",".join(str(b) for b in data)
        lines.append(f"static const uint8_t OFF_{i:02d}[] = {{{body}}};")
    lines.append("")
    arr = ",\n".join(
        f"  {{OFF_{i:02d}, sizeof OFF_{i:02d}, {f.size[0]}, {f.size[1]}}}"
        for i, f in enumerate(frames, 1))
    lines.append(f"static const BearSprite OFFLINE_SPRITES[{len(frames)}] = {{")
    lines.append(arr)
    lines.append("};")
    lines.append(f"static const int OFFLINE_SPRITE_COUNT = {len(frames)};")
    lines.append("")
    with open(HDR, "w", newline="\n") as fh:
        fh.write("\n".join(lines))


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    frames = extract()
    for i, f in enumerate(frames, 1):
        f.save(os.path.join(OUTDIR, f"{i:02d}.png"))
    emit_header(frames)
    total = sum(len(png_bytes(f)) for f in frames)
    print(f"wrote {HDR}")
    for i, f in enumerate(frames, 1):
        print(f"  OFF_{i:02d}: {f.size[0]}x{f.size[1]}")
    print(f"  total embedded: {total} bytes ({total / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
